import { Ubuntu } from "next/font/google";
import "./globals.css";

const ubuntu = Ubuntu({
  subsets: ["latin"],
  weight: ["400", "500", "300", "700"],
});

export const metadata = {
  title: "Multi-Step-Form",
  description: "Generated by create next app",
  icons: "./favicon-32x32.png",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={ubuntu.className}>{children}</body>
    </html>
  );
}
